swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /category:
    get:
      operationId: api.category.read_all
      tags:
        - Category
      summary: Read the entire set of Category
      description: Read the entire set of Category
      responses:
        200:
          description: Successfully read Category
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the cat
                name:
                  type: string
                  description: category name

    post:
      operationId: api.category.create
      tags:
        - Category
      summary: Create a Category
      description: Create a new Category
      parameters:
        - name: category
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: string
                description: uuid of the category
              name:
                type: string
                description: name of  category
      responses:
        201:
          description: Successfully created 
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the Category
              name:
                type: string
    
  /category/{category_id}:
    get:
      operationId: api.category.read_one
      tags:
        - Category
      summary: Read one Category
      description: Read one Category
      parameters:
        - name: category_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from people data operation
          schema:
            $ref: '#/definitions/Category'

    put:
      operationId: api.category.update
      tags:
        - Category
      summary: Update a Category
      description: Update a Category
      parameters:
        - name: category_id
          in: path
          description: Id the Category to update
          type: string
          required: True
        - name: category
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: name of the Category
      responses:
        200:
          description: Successfully updated Category
          schema:
            $ref: '#/definitions/Category'

    delete:
      operationId: api.category.delete
      tags:
        - Category
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: category_id
          in: path
          type: string
          description: Id of the person to delete
          required: true
      responses:
        200:
          description: Successfully deleted a person

  /product:
    get:
      operationId: api.product.read_all
      tags:
        - Product
      summary: Read the Products
      description: Read the Products
      responses:
        200:
          description: Successfully read product set operation
          schema:
            $ref: '#/definitions/AllProduct'

    post:
      operationId: api.product.create
      tags:
        - Product
      summary: Create a product
      description: Create a new product
      parameters:
        - name: product
          in: body
          description: Product to create
          required: True
          schema:
            type: object
            $ref: '#/definitions/Product'
              
      responses:
        201:
          description: Successfully created 
          schema:
            $ref: '#/definitions/Product'

definitions:
  Category:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  
  Product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      barcode:
        type: string
      price:
        type: number
      category_id:
        type: string
  AllProduct:
    type: array
    items:
      $ref: '#/definitions/Product'

