swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /category:
    get:
      operationId: api.category.read_all
      tags:
        - Category
      summary: Read the entire set of Category
      description: Read the entire set of Category
      responses:
        200:
          description: Successfully read Category
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the cat
                name:
                  type: string
                  description: category name

    post:
      operationId: api.category.create
      tags:
        - Category
      summary: Create a Category
      description: Create a new Category
      parameters:
        - name: category
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              id:
                type: string
                description: uuid of the category
              name:
                type: string
                description: name of  category
      responses:
        201:
          description: Successfully created 
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the Category
              name:
                type: string
    
  /category/{category_id}:
    get:
      operationId: api.category.read_one
      tags:
        - Category
      summary: Read one Category
      description: Read one Category
      parameters:
        - name: category_id
          in: path
          description: Id of the person to get
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people data operation
          schema:
            $ref: '#/definitions/Category'

    put:
      operationId: api.category.update
      tags:
        - Category
      summary: Update a Category
      description: Update a Category
      parameters:
        - name: category_id
          in: path
          description: Id the Category to update
          type: string
          required: True
        - name: category
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: name of the Category
      responses:
        201:
          description: Successfully updated Category
          schema:
            $ref: '#/definitions/Category'

    delete:
      operationId: api.category.delete
      tags:
        - Category
      summary: Delete a category from the people list
      description: Delete a category
      parameters:
        - name: category_id
          in: path
          type: string
          description: Id of the category to delete
          required: true
      responses:
        200:
          description: Successfully deleted a category

  /product:
    get:
      operationId: api.product.read_all
      tags:
        - Product
      summary: Read the Products
      description: Read the Products
      responses:
        200:
          description: Successfully read product set operation
          schema:
            $ref: '#/definitions/AllProduct'

    post:
      operationId: api.product.create
      tags:
        - Product
      summary: Create a product
      description: Create a new product
      parameters:
        - name: product
          in: body
          description: Product to create
          required: True
          schema:
            $ref: '#/definitions/Product'
              
      responses:
        201:
          description: Successfully created 
          schema:
            $ref: '#/definitions/Product'

  /product/{product_id}:
    get:
      operationId: api.product.read
      tags:
        - Product
      description: Read a product
      parameters:
        - name: product_id
          in: path
          type: string
          required: true
      responses:
        200:
          description: Read Certain Product
          schema:
            $ref: '#/definitions/Product'
    put:
      operationId: api.product.update
      tags:
        - Product
      summary: Create a product
      description: Create a new product
      parameters:
        - name: product_id
          in: path
          type: string
          description: Id of the product for updating
          required: true
        - name: product
          in: body
          description: Product to create
          required: True
          schema:
            $ref: '#/definitions/Product'
              
      responses:
        201:
          description: Successfully created 
          schema:
            $ref: '#/definitions/Product'

    delete:
      operationId: api.product.delete
      tags:
        - Product
      summary: Delete a product from the people list
      description: Delete a product
      parameters:
        - name: product_id
          in: path
          type: string
          description: Id of the product to delete
          required: true
      responses:
        200:
          description: Successfully deleted a product

  /order:
    post:
      operationId: api.order.create
      tags:
        - Order
      parameters:
        - name: order
          in: body
          description: Order to create
          required: True
          schema:
            $ref: '#/definitions/Order'
            
      responses:
        201:
          description: Successfully created
          schema:
            $ref: '#/definitions/Order'
  
    get:
      operationId: api.order.list
      tags:
        - Order
      parameters:
        - name: customer
          in: query
          required: False
          type: string
      
      responses:
        200:
          description: Successfully listed
          schema:
            $ref: '#/definitions/ListOrder'
            
  /order/{order_id}:
    put:
      operationId: api.order.update_status
      tags:
        - Order
      parameters:
        - name: order_id
          in: path
          required: True
          type: string
        - name: order
          in: body
          required: True
          schema:
            $ref: '#/definitions/OrderNoDetials'
      responses:
        201:
          description: Successfully update
          schema:
            $ref: '#/definitions/OrderNoDetials'
    post:
      operationId: api.order.orderdetail_add
      description: add new order item to certain order
      tags:
        - Order_Item
      parameters:
        - name: order_id
          in: path
          required: True
          type: string
        - name: order_item
          in: body
          required: True
          schema:
            $ref: '#/definitions/Order_Item'
      responses:
        201:
          description: Successfully update
          schema:
            $ref: '#/definitions/Order_Item'
    get:
      operationId: api.order.order_details
      tags:
        - Order
      parameters:
        - name: order_id
          in: path
          required: True
          type: string
      
      responses:
        200:
          description: get detail of order
          schema:
            $ref: '#/definitions/Order'
            
  /order_item/{item_id}:
    put:
      operationId: api.order.orderdetail_update
      tags:
        - Order_Item
      parameters:
        - name: item_id
          in: path
          required: true
          type: string
        - name: order_item
          in: body
          required: true
          schema:
            $ref: '#/definitions/Order_Item'
      responses:
        201:
          description: Successfully update
          
    delete:
      operationId: api.order.orderitem_delete
      tags:
        - Order_Item
      parameters:
        - name: item_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successfully delete

              
definitions:
  Category:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  
  Product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      barcode:
        type: string
      price:
        type: number
      category_id:
        type: string
  AllProduct:
    type: array
    items:
      $ref: '#/definitions/Product'
  
  Order_Item:
    type: object
    properties:
      id:
        type: string
      product_id:
        type: string
      amount:
        type: number
      item_price:
        type: number
      order_id:
        type: string
  
  Order_Item_Array:
    type: array
    items:
      $ref: '#/definitions/Order_Item'
    
  Order:
    type: object
    properties:
      id:
        type: string
      desc:
        type: string
      customer:
        type: string
      totalpayment:
        type: number
      status:
        type: string
      order_item:
        type: array
        items:
          $ref: '#/definitions/Order_Item_Array'

  OrderNoDetials:
    type: object
    properties:
      id:
        type: string
      desc:
        type: string
      customer:
        type: string
      totalpayment:
        type: number
      status:
        type: string

  ListOrder:
    type: array
    items:
      $ref: '#/definitions/OrderNoDetials'