"""empty message

Revision ID: fca1e206c78c
Revises: fec776194617
Create Date: 2018-10-09 23:43:37.212435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca1e206c78c'
down_revision = 'fec776194617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order_item', sa.Column('product_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order_item', 'product_name')
    # ### end Alembic commands ###
